### ISSUE TITLE
FSCの描画中に起こるIllegalArgumentException

### ISSUE THREAD

**Issue by Hatanas** [Jumpaku/JumpakuCurves#11]
ログを貼っておきます．
```java
java.lang.IllegalArgumentException: n(1) is too small
	at org.jumpaku.core.curve.Interval.sample(Interval.kt:26)
	at org.jumpaku.core.curve.Curve$DefaultImpls.evaluateAll(Curve.kt:27)
	at org.jumpaku.core.curve.FuzzyCurve$DefaultImpls.evaluateAll(FuzzyCurve.kt)
	at org.jumpaku.core.curve.bezier.Bezier.evaluateAll(Bezier.kt:19)
	at org.jumpaku.core.fsci.DataPreparing$Companion.extendFront(DataPreparing.kt:58)
	at org.jumpaku.core.fsci.DataPreparing.prepare(DataPreparing.kt:33)
	at org.jumpaku.core.fsci.FscGeneration.generate(FscGeneration.kt:19)
	at org.jumpaku.fxcomponents.view.CurveInput.render(CurveInput.kt:66)
	at org.jumpaku.fxcomponents.view.CurveInput.access$render(CurveInput.kt:17)
	at org.jumpaku.fxcomponents.view.CurveInput$root$1$2.handle(CurveInput.kt:49)
	at org.jumpaku.fxcomponents.view.CurveInput$root$1$2.handle(CurveInput.kt:17)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:381)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:417)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:416)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
```

例外が投げられた時の入力点列を保存する機能を作っておくとデバッグが捗ると思います．

**Comment by Jumpaku** [comment]
Fixed.
